/**
 * Rift ZoneEvents
 * Roft-ZoneEvents-Api
 *
 * OpenAPI spec version: 0.0.1
 * Contact: developer@tobiaskloss.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ZoneEvent {
    zone?: string;
    zoneId?: number;
    name?: string;
    started?: number;
}
